
{
  parserClass="com.noxlogic.saffire.intellij.plugin.parser.SaffireParser"
  stubParserClass="com.noxlogic.saffire.intellij.plugin.parser.GeneratedParserUtilBase.noxlogic.saffire.intellij.plugin.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Saffire"
  psiImplClassSuffix="Impl"
  psiPackage="com.noxlogic.saffire.intellij.plugin.psi"
  psiImplPackage="com.noxlogic.saffire.intellij.plugin.impl"

  elementTypeHolderClass="com.noxlogic.saffire.intellij.plugin.psi.SaffireTypes"
  elementTypeClass="com.noxlogic.saffire.intellij.plugin.psi.SaffireElementType"
  tokenTypeClass="com.noxlogic.saffire.intellij.plugin.psi.SaffireTokenType"
}

saffireFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY